# Use the official Jenkins image as the base
FROM jenkins/jenkins:lts

# Set the user to root to install packages
USER root

# Install necessary tools: git + docker client (docker.io)
RUN apt-get update && \
    apt-get install -y git docker.io && \
    rm -rf /var/lib/apt/lists/*

# Add Jenkins user to docker group
RUN groupadd -f docker && usermod -aG docker jenkins

# Switch back to the Jenkins user
USER jenkins

# Expose Jenkins ports
EXPOSE 8080
EXPOSE 50000
